# Generated by Django 4.0.4 on 2022-05-05 14:08

from django.db import migrations, models
import scripts.GenerateTokens


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('after_party', models.IntegerField(default=0)),
                ('qr_link', models.CharField(default=scripts.GenerateTokens.generate_qr_link, max_length=400, unique=True)),
                ('is_valid', models.IntegerField(default=1)),
            ],
        ),
    ]
