# Generated by Django 4.0.4 on 2022-05-16 18:59

from django.db import migrations, models
import scripts.GenerateTokens


class Migration(migrations.Migration):

    dependencies = [
        ('ticketdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('qr_link', models.CharField(default=scripts.GenerateTokens.generate_qr_link, max_length=400, unique=True)),
                ('is_valid', models.IntegerField(default=1)),
                ('mail_sent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PromTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('qr_link', models.CharField(default=scripts.GenerateTokens.generate_qr_link, max_length=400, unique=True)),
                ('is_valid', models.IntegerField(default=1)),
                ('mail_sent', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
